# Generated by Django 5.1.4 on 2025-02-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('teacher', 'Teacher')], default='student', max_length=10, null=True),
        ),
    ]
