# Generated by Django 5.1.5 on 2025-02-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unit',
            field=models.IntegerField(default=20),
        ),
    ]
