# Generated by Django 5.1.5 on 2025-02-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='courses',
        ),
        migrations.AddField(
            model_name='user',
            name='passed_courses',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
