# Generated by Django 5.1.5 on 2025-02-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_courses_user_passed_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selected_courses',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
