# Generated by Django 5.1.5 on 2025-02-04 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_hamniaz_course_pishniaz'),
        ('user', '0005_user_selected_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='selected_courses',
        ),
        migrations.CreateModel(
            name='selectedcourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_select', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_for', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
    ]
