# Generated by Django 5.1.5 on 2025-02-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_user_selected_courses_selectedcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selected_unit',
            field=models.IntegerField(default=0),
        ),
    ]
