# Generated by Django 5.1.4 on 2025-02-05 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_student_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
