# Generated by Django 5.1.4 on 2025-02-05 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_student_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedcourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
