# Generated by Django 5.1.5 on 2025-02-05 01:17

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='courses.department')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('credits', models.IntegerField()),
                ('classDays', models.CharField(choices=[('شنبه/دوشنبه', 'شنبه/دوشنبه'), ('یکشنبه/سشنبه', 'یکشنبه/سشنبه')], max_length=20, null=True)),
                ('startTime', models.TimeField(null=True)),
                ('endTime', models.TimeField(null=True)),
                ('pishniaz', models.IntegerField(blank=True, null=True)),
                ('hamniaz', models.IntegerField(blank=True, null=True)),
                ('examDate', django_jalali.db.models.jDateField(null=True, verbose_name='Exam Date (Jalali)')),
                ('examTime', models.TimeField(null=True, verbose_name='Exam Time')),
                ('capacity', models.IntegerField()),
                ('remainingCapacity', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.department')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.instructor')),
            ],
        ),
    ]
