# Generated by Django 5.1.5 on 2025-02-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='classDays',
            field=models.CharField(choices=[('shanbe/doshanbe', 'shanbe/doshanbe'), ('yekshanbe/seshanbe', 'yekshanbe/seshanbe')], max_length=20, null=True),
        ),
    ]
