# Generated by Django 5.1.4 on 2025-02-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_classdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='classDays',
            field=models.CharField(choices=[('شنبه/دوشنبه', 'شنبه/دوشنبه'), ('یکشنبه/سشنبه', 'یکشنبه/سشنبه')], max_length=20, null=True),
        ),
    ]
