# Generated by Django 5.1.5 on 2025-01-29 23:14

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_classtime_course_classdays_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='examTime',
        ),
        migrations.AddField(
            model_name='course',
            name='examDate',
            field=django_jalali.db.models.jDateField(null=True),
        ),
    ]
