# Generated by Django 5.1.5 on 2025-01-30 14:35

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_examdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='examTime',
            field=models.TimeField(null=True, verbose_name='Exam Time'),
        ),
        migrations.AlterField(
            model_name='course',
            name='examDate',
            field=django_jalali.db.models.jDateField(null=True, verbose_name='Exam Date (Jalali)'),
        ),
    ]
